import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import { Header } from '@/components/header'
import { Footer } from '@/components/footer'
import { ReadmeGeneratorProvider } from '@/context/readme-generator.context'
import 'highlight.js/styles/default.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`flex flex-col bg-background ${inter.className}`}>
        <Header />

        <ReadmeGeneratorProvider>
          {children}
        </ReadmeGeneratorProvider>

        <Footer />
      </body>
    </html>
  )
}
